export const arrHeaders = [
    'Origin',
    'Order',
    'Sequence',
    'Creation Date',
    'Client Name',
    'Client Last Name',
    'Client Document',
    'Email',
    'Phone',
    'UF',
    'City',
    'Address Identification',
    'Address Type',
    'Receiver Name',
    'Street',
    'Number',
    'Complement',
    'Neighborhood',
    'Reference',
    'Postal Code',
    'SLA Type',
    'Courrier',
    'Estimate Delivery Date',
    'Delivery Deadline',
    'Status',
    'Last Change Date',
    'UtmMedium',
    'UtmSource',
    'UtmCampaign',
    'Coupon',
    'Payment System Name',
    'Installments',
    'Payment Value',
    'Quantity_SKU',
    'ID_SKU',
    'Category Ids Sku',
    'Reference Code',
    'SKU Name',
    'SKU Value',
    'SKU Selling Price',
    'SKU Total Price',
    'SKU Path',
    'Item Attachments',
    'List Id',
    'List Type Name',
    'Service (Price/ Selling Price)',
    'Shipping List Price',
    'Shipping Value',
    'Total Value',
    'Discounts Totals',
    'Discounts Names',
    'Call Center Email',
    'Call Center Code',
    'Tracking Number',
    'Host',
    'GiftRegistry ID',
    'Seller Name',
    'Status TimeLine',
    'Obs',
    'UtmiPart',
    'UtmiCampaign',
    'UtmiPage',
    'Seller Order Id',
    'Acquirer',
    'Authorization Id',
    'TID',
    'NSU',
    'Card First Digits',
    'Card Last Digits',
    'Payment Approved By',
    'Cancelled By',
    'Cancellation Reason',
    'Gift Card Name',
    'Gift Card Caption',
    'Authorized Date',
    'Corporate Name',
    'Corporate Document',
    'TransactionId',
    'PaymentId',
    'SalesChannel',
    'marketingTags',
    'Delivered',
    'SKU RewardValue',
    'Is Marketplace cetified',
    'Is Checked In',
    'Currency Code',
    'Taxes',
    'Invoice Numbers',
    'Country',
    'Input Invoices Numbers',
    'Output Invoices Numbers',
    'Status raw value (temporary)',
    'Cancellation Data'
]
