export interface DnGPayload {
    Client: string,
    ClientChannel: string,
    ClientReference: string,
    CustomerName: string,
    CustomerSurname: string,
    CustomerAddress: string,
    CustomerPostalCode: string,
    CustomerTown: string,
    CustomerCountry: string,
    CustomerPhone?: string,
    CustomerCellPhone: string,
    CustomerEmail: string,
    CustomerNationalID?: string,
    ApplianceCommercialCode: string,
    ApplianceGTIN: string,
    ApplianceSerialNumber?: string,
    AppliancePurchaseDate: string,
    AppliancePurchasePrice: string,
    RegisterOnly: boolean,
    PromoCode: string,
    brand: string,
    ApplianceType?: string,
    ApplianceCommercialModel: string,
    CustomerLanguage: string
}
