//@ts-nocheck

export const keyToken = {
  frwhirlpool: {
    key: "vtexappkey-frwhirlpool-GZCPNL",
    token: "XLDJZIGVYFNRPXKIHRNGNSTFCNRNRWPFUPGNCSZTOUSTEJBYHBTCHQPFRYHMRSDBPHXZRXGORUSTAZBSLTGQDMXDZBVDLNBVRQEWLBGJUELNYWESXOAYMMYCKTAQCCDD"
  },
  frwhirlpoolqa: {
    key: "vtexappkey-frwhirlpoolqa-GESKRY",
    token: "QTGIQJQBQVBBZIABCRYNRSPSWJDCFLWSTUXVJXTSDSHTZTKBXXKACKRYDOLGGOWEYJHFLEREXFJZKVSDZBEIAWPJCYRVLNMOWCVQLEQSFFCXASNIVIHEKOECTYCMNWSK"
  },
  plwhirlpool: {
    key: "vtexappkey-plwhirlpool-EROZAI",
    token: "MMQXKOWAYMJKYZKTJCSAJJWSNGLLVFGERMBHQFESXOAYFPRJYPZQBDACQYJEDLESFETLXCDDYADVJYMYOBMGFPDOMZRRWZPLJHSBWFMVLWSBZESRMLQBZXMPAFZXLMGZ"
  },
  plwhirlpoolqa: {
    key: "vtexappkey-plwhirlpoolqa-YTJRWF",
    token: "TLEHDDRPMIEFUYYDGTBCSOLEVNHYHJUKPWPXKWQKCCUVGKUBLVZKAMPFZALQWSHCNUQYIBTJCQZQTQXLSFMMKJJCGJYJKZNJUSHMUWSKBPHJNZMIDAYQFVRDKORYDJZC"
  }
}

export const enabledCredentials = {
  "frwhirlpool":[
    {
      key: "vtexappkey-frwhirlpool-GZCPNL",
      token: "XLDJZIGVYFNRPXKIHRNGNSTFCNRNRWPFUPGNCSZTOUSTEJBYHBTCHQPFRYHMRSDBPHXZRXGORUSTAZBSLTGQDMXDZBVDLNBVRQEWLBGJUELNYWESXOAYMMYCKTAQCCDD"
    },
    {
      key: "vtexappkey-frwhirlpool-QCRZJB",
      token: "YMXZGZSQCTQJHOXHPHLTPUGZAFLXSRJVONLVTECVDGEQRMMIARKNJEREGYYAOVXLJVUUCCOLEPQIPPHOTCWBGVLKWHOUFBHHITHWRSFYCZJUNIORQKHLZWENJKYVNTFD"
    }
  ],
  "frwhirlpoolqa":[
    {
      key: "vtexappkey-frwhirlpoolqa-GESKRY",
      token: "QTGIQJQBQVBBZIABCRYNRSPSWJDCFLWSTUXVJXTSDSHTZTKBXXKACKRYDOLGGOWEYJHFLEREXFJZKVSDZBEIAWPJCYRVLNMOWCVQLEQSFFCXASNIVIHEKOECTYCMNWSK"
    },
    {
      key: "vtexappkey-frwhirlpoolqa-CXFDXU",
      token: "REUXJQOILDOJFAMXOWMWYYZBOLVDXKELBOUZRCXDNKASPPAJYHJLXFHTFSIYVKLAZCHRGNGLZIJNXHLZLLFQATOWGAUYUZICZZSNHJDLAYMPVTWXHJMKFUZGOKKFSIRA"
    }
  ],
  "plwhirlpool":[
    {
      key: "vtexappkey-plwhirlpool-EROZAI",
      token: "MMQXKOWAYMJKYZKTJCSAJJWSNGLLVFGERMBHQFESXOAYFPRJYPZQBDACQYJEDLESFETLXCDDYADVJYMYOBMGFPDOMZRRWZPLJHSBWFMVLWSBZESRMLQBZXMPAFZXLMGZ"
    },
    {
      key: "vtexappkey-plwhirlpool-TAKLTH",
      token: "YYNCVDAJLRHMJVXOJVNBPZGEVBPELLFFJYYAJFKQYVLKYRBNIJZXTBKYSJHUNVXZLBCKXXFELXCTOVGDACWCMIMIOZIZXQCCXMYWOQQLDVLVYQKWDETLZVNDPUVXPFGU"
    }
  ],
  "plwhirlpoolqa":[
    {
      key: "vtexappkey-plwhirlpoolqa-YTJRWF",
      token: "TLEHDDRPMIEFUYYDGTBCSOLEVNHYHJUKPWPXKWQKCCUVGKUBLVZKAMPFZALQWSHCNUQYIBTJCQZQTQXLSFMMKJJCGJYJKZNJUSHMUWSKBPHJNZMIDAYQFVRDKORYDJZC"
    },
    {
      key: "vtexappkey-plwhirlpoolqa-QZAEEZ",
      token: "XMZKOYGPKCOFYKGWBNVUBVVPTYXMFZXILTIVSEWEQACGBIIXMDLNVGNCQJQQBTKLFFTFCLEWQREBTPOLPZACOKNEFFEIOFCWQRBVODUBYOWECMJBUFBBTHWUSOZWHVIK"
    }
  ]
}
