const states = [
  { value: 'ARA', label: 'Auvergne-Rhône-Alpes' },
  { value: 'BFC', label: 'Bourgogne-Franche-Comté' },
  { value: 'BRE', label: 'Bretagne' },
  { value: 'CVL', label: 'Centre-Val de Loire' },
  { value: 'COR', label: 'Corse' },
  { value: 'GES', label: 'Grand Est' },
  { value: 'HDF', label: 'Hauts-de-France' },
  { value: 'IDF', label: 'Île-de-France' },
  { value: 'NOR', label: 'Normandie' },
  { value: 'NAQ', label: 'Nouvelle-Aquitaine' },
  { value: 'OCC', label: 'Occitanie' },
  { value: 'PDL', label: 'Pays de la Loire' },
  { value: 'PAC', label: 'Provence-Alpes-Côte d\'Azur' },
  { value: 'CP', label: 'Clipperton' },
  { value: 'GP', label: 'Guadeloupe' },
  { value: 'GF', label: 'Guyane' },
  { value: 'MQ', label: 'Martinique' },
  { value: 'YT', label: 'Mayotte' },
  { value: 'NC', label: 'Novelle-Calédonie' },
  { value: 'PF', label: 'Polynésie' },
  { value: 'PM', label: 'Saint-Pierre-et-Miquelon' },
  { value: 'BL', label: 'Saint Barthélemy' },
  { value: 'MF', label: 'Saint Martin' },
  { value: 'RE', label: 'Réunion' },
  { value: 'TF', label: 'Terres Australes Françaises' },
  { value: 'WF', label: 'Wallis-et-Futuna' },
  // English Provinces
  { value: 'ENG', label: 'England' },
  { value: 'NIR', label: 'Northern Ireland' },
  { value: 'SCT', label: 'Scotland' },
  { value: 'WLS', label: 'Wales' }
]
export default states