const fs = require('fs')

let array = 
[
    "vtex.admin                        ","4.51.1                                           ",
"vtex.admin-account-details        ","1.0.1                                            ",
"vtex.admin-apps                   ","4.3.0                                            ",
"vtex.admin-audit                  ","2.9.0                                            ",
"vtex.admin-binding                ","0.28.0                                           ",
"vtex.admin-cms                    ","1.17.7                                           ",
"vtex.admin-collections            ","0.164.0                                          ",
"vtex.admin-coupons                ","0.3.5                                            ",
"vtex.admin-defense-mode           ","0.4.2                                            ",
"vtex.admin-docs                   ","0.5.2                                            ",
"vtex.admin-home                   ","3.9.1                                            ",
"vtex.admin-insights               ","4.6.1                                            ",
"vtex.admin-inventory              ","0.50.0                                           ",
"vtex.admin-login                  ","1.25.1                                           ",
"vtex.admin-logistics              ","1.43.0                                           ",
"vtex.admin-offer-quality          ","0.4.3                                            ",
"vtex.admin-orders                 ","0.146.1                                          ",
"vtex.admin-pages                  ","4.51.2                                           ",
"vtex.admin-payment-affiliations   ","0.1.1                                            ",
"vtex.admin-pickup-points          ","2.14.1                                           ",
"vtex.admin-pricing-settings       ","1.7.0                                            ",
"vtex.admin-promotions             ","1.6.4                                            ",
"vtex.admin-sales-performance      ","1.4.3                                            ",
"vtex.admin-sellers                ","1.5.5                                            ",
"vtex.admin-sku-binding            ","0.6.0                                            ",
"vtex.admin-sponsor                ","1.1.0                                            ",
"vtex.admin-suggestions            ","2.37.1                                           ",
"vtex.admin-users                  ","1.17.1                                           ",
"vtex.admin-vendor-invite          ","0.13.0                                           ",
"vtex.admin-wallet-hub             ","0.3.0                                            ",
"vtex.app-install-monitor          ","0.1.1                                            ",
"vtex.asset-server                 ","0.15.5                                           ",
"vtex.audit-io                     ","0.1.4                                            ",
"vtex.auth-admin                   ","3.63.0                                           ",
"vtex.auth-server                  ","0.18.0                                           ",
"vtex.billing                      ","0.24.1                                           ",
"vtex.broadcaster                  ","0.9.0                                            ",
"vtex.builder-hub                  ","0.293.4                                          ",
"vtex.cartman                      ","0.3.1                                            ",
"vtex.checkout                     ","0.6.0                                            ",
"vtex.client-admin-settings        ","0.9.1                                            ",
"vtex.colossus-legacy-proxy        ","2.3.5                                            ",
"vtex.developer-docs-integration   ","0.5.6                                            ",
"vtex.dotnet-messenger-sender      ","0.1.7                                            ",
"vtex.evolution-manager-graphql    ","0.15.3                                           ",
"vtex.file-manager                 ","0.11.0                                           ",
"vtex.frontend-metrics-gateway     ","0.7.0                                            ",
"vtex.google-pay                   ","1.2.1                                            ",
"vtex.invoice-notifier             ","0.8.2                                            ",
"vtex.marketplace-network          ","0.25.6                                           ",
"vtex.messages-templates           ","0.10.1                                           ",
"vtex.messenger-core               ","0.1.9                                            ",
"vtex.mkp-category-mapper-ui       ","1.21.0                                           ",
"vtex.my-account                   ","1.27.0                                           ",
"vtex.my-authentication            ","1.7.0                                            ",
"vtex.myuser-io                    ","2.19.2                                           ",
"vtex.notification-generator       ","0.6.2                                            ",
"vtex.omnishipping                 ","1.13.11-hkignore.hotpoint-0                      ",
"vtex.order-auth                   ","1.8.1                                            ",
"vtex.orders-broadcast             ","0.3.2                                            ",
"vtex.pix-payment                  ","0.12.2                                           ",
"vtex.promotions-simulator         ","0.3.0                                            ",
"vtex.request-capture              ","2.3.0                                            ",
"vtex.reverse-registry             ","0.6.14                                           ",
"vtex.rewriter                     ","1.57.3                                           ",
"vtex.sales-performance-graphql    ","0.8.1                                            ",
"vtex.seller-provisioner           ","0.2.1                                            ",
"vtex.seller-welcome               ","0.3.2                                            ",
"vtex.shipping-preview             ","0.14.1                                           ",
"vtex.sms-messenger-sender         ","0.1.0                                            ",
"vtex.smtp-messenger-sender        ","0.1.0                                            ",
"vtex.sno                          ","0.0.3                                            ",
"vtex.sse-server                   ","0.3.3                                            ",
"vtex.store                        ","2.131.1                                          ",
"vtex.store-sitemap                ","2.15.0                                           ",
"vtex.support-center               ","1.3.0                                            ",
"vtex.toolbelt-telemetry           ","0.1.3                                            ",
"vtex.transform-handlebars-email   ","0.1.12                                           ",
"vtex.transform-handlebars-sms     ","0.1.4                                            ",
"vtex.transform-render-email       ","0.1.7                                            ",
"vtex.transform-render-sms         ","0.1.7                                            ",
"vtex.workspace-analytics          ","0.1.7                                            ",
"hotpointuk.add-to-cart-custom                      ","0.2.4                           ",
"hotpointuk.analytics-wrapper-component             ","0.1.3                           ",
"hotpointuk.api-wrapper                             ","0.2.1                           ",
"hotpointuk.awarded-logos                           ","0.0.3                           ",
"hotpointuk.back-in-stock-service                   ","0.0.7                           ",
"hotpointuk.billing-address                         ","0.0.15                          ",
"hotpointuk.blog-article-page                       ","2.0.8                           ",
"hotpointuk.bom-page                                ","0.0.10                          ",
"hotpointuk.bom-redirect                            ","0.0.10                          ",
"hotpointuk.bredcrumbs                              ","0.1.3                           ",
"hotpointuk.carousel-salesforce                     ","0.0.3                           ",
"hotpointuk.catalog-export                          ","0.2.1                           ",
"hotpointuk.catalog-filter-label                    ","0.0.3                           ",
"hotpointuk.category-videos                         ","0.0.3                           ",
"hotpointuk.checkout-container-custom               ","0.2.13                          ",
"hotpointuk.checkout-hdx-delivery-slots-uk          ","0.0.19                          ",
"hotpointuk.checkout-shipping-summary               ","0.0.11                          ",
"hotpointuk.checkout-v6-ptv-uk                      ","0.1.9                           ",
"hotpointuk.checkout-v6-tradeplace-delivery-uk      ","1.0.5                           ",
"hotpointuk.condition-layout                        ","0.0.3                           ",
"hotpointuk.conditional-login                       ","0.0.3                           ",
"hotpointuk.custom-additional-services              ","0.0.6                           ",
"hotpointuk.custom-datetime                         ","0.0.6                           ",
"hotpointuk.custom-form                             ","0.0.18                          ",
"hotpointuk.custom-phone-number-uk                  ","0.0.7                           ",
"hotpointuk.custom-products-list                    ","0.0.4                           ",
"hotpointuk.custom-search                           ","0.0.6                           ",
"hotpointuk.discontinued-products                   ","0.0.5                           ",
"hotpointuk.domande-frequenti                       ","0.1.18                          ",
"hotpointuk.dropdown                                ","0.0.4                           ",
"hotpointuk.dropdown-show-images                    ","0.0.3                           ",
"hotpointuk.fast-est-pdp                            ","0.0.4                           ",
"hotpointuk.flixmedia-whl                           ","0.0.4                           ",
"hotpointuk.genesys                                 ","0.1.4                           ",
"hotpointuk.gtm-whirlpool                           ","0.1.7                           ",
"hotpointuk.hdx-connector                           ","1.0.14                          ",
"hotpointuk.head-json-component                     ","0.0.5                           ",
"hotpointuk.hotpoint-b2c-uk                         ","0.0.13                          ",
"hotpointuk.hotpoint-theme                          ","7.0.1                           ",
"hotpointuk.hreflang-home-component                 ","0.0.5                           ",
"hotpointuk.infinity-tracking                       ","0.0.3                           ",
"hotpointuk.inject-title-tag                        ","0.0.2                           ",
"hotpointuk.key-features                            ","0.1.2                           ",
"hotpointuk.key-informations                        ","0.1.1                           ",
"hotpointuk.lead-time                               ","0.1.1                           ",
"hotpointuk.models                                  ","0.0.8                           ",
"hotpointuk.new-relic                               ","0.0.4                           ",
"hotpointuk.obsolete-product-banner                 ","0.0.2                           ",
"hotpointuk.order-placed                            ","0.1.3                           ",
"hotpointuk.out-of-stock-products                   ","0.0.8                           ",
"hotpointuk.pdp-query-with-modal                    ","0.0.2                           ",
"hotpointuk.pdp-structured-data                     ","0.1.3                           ",
"hotpointuk.plp-structured-data                     ","0.0.3                           ",
"hotpointuk.popup-custom                            ","0.4.0                           ",
"hotpointuk.print-specification                     ","0.0.1                           ",
"hotpointuk.product-image                           ","0.0.5                           ",
"hotpointuk.product-specifications-with-rules       ","1.0.15                          ",
"hotpointuk.promo-countdown                         ","0.0.1                           ",
"hotpointuk.purchase-context                        ","0.0.7                           ",
"hotpointuk.read-more                               ","0.1.2                           ",
"hotpointuk.reevoo                                  ","0.0.9-beta.0                    ",
"hotpointuk.reevoo-snippets                         ","1.0.1                           ",
"hotpointuk.repair-page                             ","0.0.1                           ",
"hotpointuk.search-bar-custom                       ","0.0.2                           ",
"hotpointuk.servizi-aggiuntivi-pdp                  ","1.0.14                          ",
"hotpointuk.share-button                            ","0.1.1                           ",
"hotpointuk.show-more                               ","0.0.2                           ",
"hotpointuk.slider-layout                           ","0.0.3                           ",
"hotpointuk.video-player-thron-pdp                  ","0.0.49                          ",
"hotpointuk.visibility-layout                       ","0.0.7                           ",
"hotpointuk.warehouse-syncher                       ","0.0.7                           ",
"hotpointuk.where-to-buy                            ","0.0.40                          ",
"hotpointuk.youreko                                 ","0.0.27                          ",
"hotpointuk.youreko-settings                        ","0.0.31                          ",
"vtex.admin-graphql-ide                             ","3.7.0                           ",
"vtex.admin-search                                  ","1.70.2                          ",
"vtex.admin-v4-docs                                 ","0.2.0                           ",
"vtex.admin-webpage-performance                     ","0.1.1                           ",
"vtex.checkout-ui-custom                            ","0.12.7                          ",
"vtex.checkout-ui-settings-server                   ","0.4.2-hkignore.europe-0         ",
"vtex.lengow                                        ","0.1.16                          ",
"vtex.partytown                                     ","1.0.1-beta.0                    ",
"vtex.payment-provider-test-suite                   ","4.1.1                           ",
"vtex.provider-manager-installer                    ","0.2.0                           ",
"vtex.reviews-and-ratings                           ","2.12.8                          ",
"vtex.search-resolver                               ","1.65.1                          ",
"vtex.wish-list                                     ","1.16.0                          ",
"vtexeurope.checkout-v6-terms-conditions            ","1.0.1                           ",
"vtexeurope.hide-cancellation-request               ","1.2.0                           ",
"whirlpoolemea.black-friday-registration-form       ","0.0.9                           ",
"whirlpoolemea.cookie-table                         ","1.0.11                          ",
"whirlpoolemea.crm-async-integration                ","0.3.14                          ",
"whirlpoolemea.crm-profiling                        ","0.0.1                           ",
"whirlpoolemea.faq                                  ","0.0.2                           ",
"whirlpoolemea.google-site-verification             ","1.0.0                           ",
"whirlpoolemea.google-tag-manager                   ","2.2.31                          ",
"whirlpoolemea.helmet-custom-app                    ","1.0.4                           ",
"whirlpoolemea.image-from-specification             ","1.0.0                           ",
"whirlpoolemea.import-widget-from-sandwatch         ","2.4.7                           ",
"whirlpoolemea.login-custom-flow                    ","1.1.13                          ",
"whirlpoolemea.newsletter-custom-app                ","0.0.9                           ",
"whirlpoolemea.order-reservation-handler            ","1.0.3                           ",
"whirlpoolemea.page-rewriter                        ","1.0.3                           ",
"whirlpoolemea.paypal-app                           ","1.0.6                           ",
"whirlpoolemea.pixel-my-account-app                 ","1.1.1                           ",
"whirlpoolemea.product-specifications-with-images   ","2.0.3                           ",
"whirlpoolemea.remote-html-embed                    ","3.0.0                           ",
"whirlpoolemea.sfmc-integration                     ","2.1.12                          ",
"whirlpoolemea.store-link-custom                    ","1.1.12                          ",
"whirlpoolemea.stripe-custom                        ","0.0.5                           ",
"whirlpoolemea.timer-component                      ","0.0.4                           ",
"whirlpoolemea.worldpay-connector                   ","1.0.5                           ",
"whirlpoolemea.worldpay-payment-app                 ","1.0.1                           "
]


let arrayNoWS = removeWhitespaces(array)
let csvFile = arrayToCSV(arrayNoWS);


function removeWhitespaces(array) {
    return array.map(function(element) {
        return element.trim();
    });
}



function arrayToCSV(array) {
    let csv = '';

    for (let i = 0; i < array.length; i += 2) {
        csv += array[i] + ',' + array[i + 1] + '\n';
    }

    return csv;
}
console.log(csvFile);

fs.writeFileSync("./hotpointuk.csv", csvFile);

