query getSLRegions($brand: String!, $country: String!, $locale: String!, $country_id: String!) {
    getSLRegions(brand: $brand, country: $country, locale: $locale, country_id: $country_id) @context(provider:"whirlpoolemea.service-locator-api-locations") { 
        locations{
            count
            results{
                id
                label
                slug
                parent_label
            }
        }
    }
}