query getSLCities($brand: String!, $country: String!, $locale: String!, $country_id: String!, $province: String!, $region: String!) {
    getSLCities(brand: $brand, country: $country, locale: $locale, country_id: $country_id, province: $province, region: $region) @context(provider:"whirlpoolemea.service-locator-api-locations") { 
        locations{
            count
            results{
                id
                label
                slug
                parent_label
            }
        }
    }
}