//@ts-nocheck

export const vtexKeyToken = {
  "itwhirlpoolqa": {
    key: 'vtexappkey-itwhirlpoolqa-SETTVR',
    token: 'IZQLNOEVVJGXTAQPMNBMQWOGJYLYVWHEEHMCHEBQAJYMMTBSCPLWNBILLJBPCFAYCBSLOOIHMKMGYBUPWTWGLKQDZARXCMNUJZJKAPENGDKCOBMJPLSJITNRKPMNXLFZ'
  },
  "itwhirlpool": {
    key: 'vtexappkey-itwhirlpool-YKHNOZ',
    token: 'SSUBFODAEAHOAJGTKHQCDKSPEGFFIOESKDESZSVSATMETJPLFSNZQFDHAEXYIYSQVPEWFNUSLXCKYOVUQUZPAFCEAWSUUXJBBVIEESFSYVOSDSJMICIOYCQQNAWIVAXO'
  },
  "ruwhirlpoolqa": {
    key: 'vtexappkey-ruwhirlpoolqa-AIHWUB',
    token: 'TIRFJIUDXGCJUZPCGOIOUUZOKQGEAOXOIVGWLRFORGCDBDTVPDRGMXDYJDVSBQCJINAYTTQOIUWORVMHXKOWXRCKRHMIWMMBDTVOCUBVMCXSBPHOQNVQBGMQLPHMHISW'
  },
  "ruwhirlpool": {
    key: ' vtexappkey-ruwhirlpool-ZRRZBV',
    token: 'MJSOJAPHHFPCSZQMAAVACENUEAXRMMSQUKLOZMGFDXQAJMQINYVRLWEIVYKICYVUMZIHOCNOTQXENNKRKPDORAEYGCSBBYCECWNKEJUKKGXVYAVIOSXNUGDLUJBLJMNU'
  },
  "frwhirlpoolqa": {
    key: 'vtexappkey-frwhirlpoolqa-GESKRY',
    token: 'QTGIQJQBQVBBZIABCRYNRSPSWJDCFLWSTUXVJXTSDSHTZTKBXXKACKRYDOLGGOWEYJHFLEREXFJZKVSDZBEIAWPJCYRVLNMOWCVQLEQSFFCXASNIVIHEKOECTYCMNWSK'
  },
  "frwhirlpool": {
    key: 'vtexappkey-frwhirlpool-GZCPNL',
    token: 'XLDJZIGVYFNRPXKIHRNGNSTFCNRNRWPFUPGNCSZTOUSTEJBYHBTCHQPFRYHMRSDBPHXZRXGORUSTAZBSLTGQDMXDZBVDLNBVRQEWLBGJUELNYWESXOAYMMYCKTAQCCDD'
  },
  "frccwhirlpool": {
    key: 'vtexappkey-frccwhirlpool-TLEGNP',
    token: 'PLCALEQQTDIREVQHZGGEHSFUCRXMCXZRERHFWAYBZQLDDOVNIUNXQHWWFIYUGDOWERNMOLLYHEEQGCQNWJEHKBBWVKZNCEUWCPZMBIZWJOPLDFQCSKYWYGMCPQQDLXVD'
  },
  "frccwhirlpoolqa": {
    key: 'vtexappkey-frccwhirlpoolqa-XVPFIN',
    token: 'PXFKJDNHAVUTNTJPGYQDRUWXDFCWNJQDNFJDZFPOUNICQLJCTVUAHGPVAIGDBQTQFQGIKFQAIBJELUGRVADSPQVGPNCRYMNETRWAFBRNFTSGXLKGBPIBNBBPUZSWDZBW'
  },
  "plwhirlpool": {
    key: 'vtexappkey-plwhirlpool-EROZAI',
    token: 'MMQXKOWAYMJKYZKTJCSAJJWSNGLLVFGERMBHQFESXOAYFPRJYPZQBDACQYJEDLESFETLXCDDYADVJYMYOBMGFPDOMZRRWZPLJHSBWFMVLWSBZESRMLQBZXMPAFZXLMGZ'
  },
  "plwhirlpoolqa": {
    key: "vtexappkey-plwhirlpoolqa-YTJRWF",
    token: "TLEHDDRPMIEFUYYDGTBCSOLEVNHYHJUKPWPXKWQKCCUVGKUBLVZKAMPFZALQWSHCNUQYIBTJCQZQTQXLSFMMKJJCGJYJKZNJUSHMUWSKBPHJNZMIDAYQFVRDKORYDJZC"
  }
}
