//@ts-nocheck

export const vtexKeyToken = {
  "hotpointit" : {
    key: 'vtexappkey-hotpointit-INZJFJ',
    token: 'QCABLVHTDVRXALJPDTOJRDILYSJXEGFCTAQFQTJNPKGGWKLBVNUPGYOMUPCSMKPWQODAVEYKJATGXCONGHBRLPVVMDLBQQBFVJQHHLGROKFFEHPSAOLEIYLATHNRTXTT'
  },
  "hotpointitqa" : {
    key: 'vtexappkey-hotpointitqa-EPFPPN',
    token: 'DILJGPARWWWUXBGKRDYODOYFSWTHJOFUUMKJWZJMIRYGTPWZKCLBDJFPKFRKWTHIQBALRWNRTMGMQRLCATXHDDRKGUZQIZQPJQPSPKINOTIQDTZSUOJCWAFNJPEWXWJT'
  }
}

export const cipherKey = "36246a8fcf66b68a0cffe0eb70b7e63b";
export const cipherIV = "36f2d92fbc013353";