query ($query: RecipeInput) {
  queryRecipes(query: $query) {
    page {
      totalRowCount
      pageSize
      pageNumber
    }
    facets {
      name
      values
    }
    recipes {
      id
      name
      type
      category
      preparationTime
      cookTime
      chefplusTime
      supremeChefTime
      imageDesktop
      imageMobile
      imageCard
      description
      mainIngredients
      ingredients
      steps
      images
      relatedRecipes
    }
  }
}
