query ($query: RecipeInput) {
  queryRecipes(query: $query) {
    recipes {
      id
      name
      type
      category
      imageDesktop
      imageMobile
      imageCard
      description
      images
    }
  }
}
